<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>nng</RootNamespace>
    <MSBuildTreatWarningsAsErrors>true</MSBuildTreatWarningsAsErrors>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt" Pack="true" PackagePath="licenses"/>
    <None Include="..\README.md" Pack="true" PackagePath="$(PackageReadmeFile)"/>
  </ItemGroup>

  <PropertyGroup>
    <VersionPrefix>1.7.0</VersionPrefix>
    <VersionSuffix></VersionSuffix>
    <Authors>Jeikabu</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Owners>Jeikabu</Owners>
    <PackageProjectUrl>https://github.com/rodrigo455/nng.NETCore</PackageProjectUrl>
    <Summary>.NET Core bindings to nng</Summary>
    <PackageTags>nanomsg nng csnng</PackageTags>
    <Description>.NET Core bindings to nng (https://github.com/nanomsg/nng)</Description>
    <RepositoryUrl>https://github.com/rodrigo455/nng.NETCore</RepositoryUrl>
  </PropertyGroup>
</Project>
